### ISSUE TITLE
Unity Android Build - Camera lagging/jittering while using azure sample

### ISSUE THREAD

**Issue by cribin** [Azure/azure-spatial-anchors-samples#83] opened 2019-11-07 14:45 UTC
When I tried out the Unity Sample AzureSpatialAnchorsNearbyDemo for Android I experience a jittering/lagging of the Videofeed after I place the first anchor and the demo asks me to scan more of the environment). Here is a video demonstrating the problem: https://drive.google.com/file/d/1x6USlVO9hN72hBSammzVUM1zIzNNT7Wf/view?usp=sharing

When I commented out the code at line 180 in the script Assets/AzureSpatialAnchors.SDK/Scripts/SpatialAnchorManager.cs (session.ProcessFrame(xRCameraFrame.nativePtr.GetPlatformPointer());), the jittering stopped. 
Does anyone know what causes the jittering? Could it be an issue with the phone? 

More information:
Unity Version: 2019.141f
Platform: Android
Phone Model: Xiaomi Pocophone f1

**Comment by craigktreasure** [comment] 2019-11-14 18:29
Hey @cribin, sorry to hear you're having issues. We are aware of a performance issue in Unity that you may also be hitting on your specific device. We're waiting on a fix from Unity, but a workaround you can try in the meantime is to add a couple of objects to your scene that cast shadows. We've had success on a few other devices with this workaround. I'm not 100% sure that you're hitting the same issue, but it's worth a try. Please let me know.

**Comment by DaneyT** [comment] 2019-11-25 13:59
I encountered the same problem, just leaving my setup info here:
Unity Version: 2019.1.2f1
Platform: Android
Tablet: Samsung Galaxy S6 Tab

But works fine on Google Pixel 1 and Samsung Galaxy S9 smartphones (Unity Version: 2019.1.2f1)

**Comment by darax** [comment] 2020-04-16 00:10
dupe of https://github.com/Azure/azure-spatial-anchors-samples/issues/86

**Closed by darax** 2020-04-16 00:10 UTC
