### ISSUE TITLE
Unable to retrieve anchors created on other platforms in one Spatial Anchor Account

### ISSUE THREAD

**Issue by anders-lundgren** [Azure/azure-spatial-anchors-samples#175] opened 2020-05-22 19:25 UTC
I'm building an app that uses Coarse Relocalization to locate spatial anchors. I have two spatial anchor accounts that I use for testing. In one account, I am able to create, and locate, anchors normally between Android and iOS devices.
Using the same app, I then switch to my other spatial anchors account, but this time the app is only able to locate anchors that are created on its own platform (Android created anchors on Android devices etc). When enumerating nearby anchors in the space, I find all 16 anchors, but only about half get located on each platform (I have set the watcher limit to 25 anchors).
Devices tested: 
iPhone X
Google Pixel 4
Spatial Anchors 2.2.1
Unity 2019.2.17f1
Any ideas where to start looking?

**Comment by bucurb** [comment] 2020-05-25 08:38
Could you e-mail me your Spatial Anchors accounts GUIDs please? We'll need to track your activity on the service side to be able to figure-out why it's failing to reloc to all the anchors. Also, if you have your ResCv ids handy (they'd normally be printed-out in logcat, there's one for each service session). it would be good to get them as well, as that would narrow-down to the exact session with the failure.

**Comment by anders-lundgren** [comment] 2020-06-01 09:12
Thanks @bucurb, I have emailed you the account GUIDs. Will try and run some sessions and see if I can capture the ResCv ID:s as well.

**Comment by pabusse** [comment] 2020-06-11 11:09
Hi @anders-lundgren,

Thank you for providing the account details.
With these, I was able to find out why your queries from different platforms were not matched up.

When you performed the queries, the Android and iOS devices were reporting locations about 35 meters apart. This can be explained by each OS relying on a different provider for network-resolved location when there is no GPS reception, and the underlying datasets may not always agree.

On the first account you provided, the query found about 980 anchors which could have potentially matched, so we only processed the 64 closest ones to the phone's reported position.
Now, you mention that there were only 16 anchors nearby so we should have still been able to search out far enough from either phone's position to find all of them.
To understand the discrepancy it's worth knowing that the service keeps around the visual data of past anchors even after they are no longer being referenced, and will still attempt to match them because it may find a pose indirectly from the connectivity of the pose graph.

The second account was more fresh and did not have as many deleted anchors guiding the search away from the correct location.

In general, it's better to use Wi-Fi or Bluetooth beacons indoors because the network-resolved location can be inaccurate.

Since iOS restricts access to the raw Wi-Fi signals, Bluetooth beacons are the recommended solution for large indoor areas which need to be mapped across all three platforms. This does require deploying additional hardware and configuring the session to know about the reference beacons' UUIDs, so I fully understand if this is not be a feasible solution for you.

We are constantly improving the service and hope to better support this scenario in the future.

**Comment by anders-lundgren** [comment] 2020-06-12 15:36
Hi @pabusse , great info, thanks! 
I found that the distance between the estimated locations is only a few metres in lat/long but 30+ metres in altitude. Is there any way to only search using lat/long?  

On a related note, I am very curious if there is some public information about the behaviour you're mentioning, ie that you're keeping anchor data for future reference? This makes perfect sense in most cases, but, I've found, that similarly to how the HoloLens can sometimes get confused about the geometry of a space, warping it so that some areas are incorrectly aligned. 

Also, is there any way, to be allowed to view the resulting point cloud (without features), of this particular space? I have a feeling that it is quite mangled in all 10+ accounts that we have used during testing and it would be interesting to learn where it gets confused. 

Second side note: Both HL1 and HL2 get profusely confused in this particular space, forcing me to delete all spaces for the devices to function properly again, indicating that there is some aggravating factor at play here. The place is well lit, with lots of visual features. My best guess is that the starkly patterned floor tiles may be causing some of these issues, could this be possible? 
![image](https://user-images.githubusercontent.com/5128590/84519990-2827df00-acd3-11ea-90a7-9cb5a345e58f.png)

**Comment by craigktreasure** [comment] 2020-09-09 03:33
@pabusse, would you mind following up with the remaining questions? Thanks!

**Comment by pabusse** [comment] 2020-09-09 09:06
@anders-lundgren Sorry for not getting to this earlier!

> Is there any way to only search using lat/long?

We do already find anchors even if your altitude reading happens to be completely wrong. However, if there are too many anchors in a location, we will prioritize the ones that appear to be closer in a second phase.

There is no way at this time to selectively ignore altitude for this ranking.

> On a related note, I am very curious if there is some public information about the behaviour you're mentioning, ie that you're keeping anchor data for future reference? This makes perfect sense in most cases, but, I've found, that similarly to how the HoloLens can sometimes get confused about the geometry of a space, ASA occasionally seems to be warping spaces a bit so that some areas are incorrectly aligned.

We take advantage of additional visual data in two ways. [Relationships between anchors](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/anchor-relationships-way-finding) help us find an anchor indirectly by finding a known-nearby anchor. Each anchor individually [evolves with additional view points from which it was scanned during queries](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/guidelines-effective-anchor-experiences#anchor-improvement-over-time).

We are working hard to improve the robustness of the mapping algorithms to prevent the types of failures you were seeing.

> Also, is there any way, to be allowed to view the resulting point cloud (without features), of this particular space? I have a feeling that it is quite mangled in all 10+ accounts that we have used during testing and it would be interesting to learn where it gets confused.

In general, we do not have access to customer's mapped spaces, however there are internal tools which we use to visualize our own point cloud reconstructions. If you capture a [diagnostics bundle](https://docs.microsoft.com/en-us/azure/spatial-anchors/concepts/logging-diagnostics#diagnostics-logging) for a session that works as intended and a session that doesn't, we might be able to help you pinpoint what is causing the locations to get mixed up.

> Second side note: Both HL1 and HL2 get profusely confused in this particular space, forcing me to delete all spaces for the devices to function properly again, indicating that there is some aggravating factor at play here. The place is well lit, with lots of visual features. My best guess is that the starkly patterned floor tiles may be causing some of these issues, could this be possible?

Yes, repetitive features can cause visual wormholes. We are looking at ways to detect these and require additional visual confirmation in those cases.

**Comment by msftradford** [comment] 2020-11-17 22:58
Hi @anders-lundgren, I'm going to close this issue. Feel free to re-open if your questions were not sufficiently addressed. thanks!

**Closed by msftradford** 2020-11-17 22:58 UTC
