### ISSUE TITLE
ASA iOS would not build

### ISSUE THREAD

**Issue by ttkrpink** [Azure/azure-spatial-anchors-samples#277] opened 2021-07-25 01:20 UTC
ASA iOS would not build
clean project，Unity 2021，ASA 2.10.2，mrtk 2.7.2，Openxr. Play mode works fine. build failed with errors as shown
![6B05F50F-C4A4-432A-BD05-19F8EA25F673](https://user-images.githubusercontent.com/2522889/126884694-069f55d4-2ce7-4d66-bb5b-984b7dab2634.png)

**Comment by pamistel** [comment] 2021-07-28 11:35
This is a duplicate of [the issue ](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/37)filed on the OpenXR sample. Closing this one.

**Closed by pamistel** 2021-07-28 11:35 UTC
