### ISSUE TITLE
Warnings in Unity editor about conflicting definitions (2.4.0)

### ISSUE THREAD

**Issue by ephb** [Azure/azure-spatial-anchors-samples#205] opened 2020-08-11 10:30 UTC
Hi,

 **Description**
There are 190 warnings in in the console about conflicting definitions between AzureSpatialAnchorsBridge_UnityEditor.cs and the assembly.
This should not have any impact on the users ability to build and run the samples but is undesired behavior nonetheless and cause the user the skip over other warnings.

**Steps to reproduce the issue**

1. Create a new Unity 2019.4 project
2. Import the ASA Unity package
3. Switch platform to iOS or Android
4. See 190 warning appear in the console

**Expected behavior**

This should not happen.

**Additional context**
All of the warnings are the same, the only difference is the type definition they are referencing.

Assets\AzureSpatialAnchors.SDK\Plugins\Editor\AzureSpatialAnchorsBridge_UnityEditor.cs(1382,94): warning CS0436: The type 'AnchorLocatedEventArgs' in 'C:\Unity Projects\Azure Bug Test\Assets\AzureSpatialAnchors.SDK\Plugins\Editor\AzureSpatialAnchorsBridge_UnityEditor.cs' conflicts with the imported type 'AnchorLocatedEventArgs' in 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Unity Projects\Azure Bug Test\Assets\AzureSpatialAnchors.SDK\Plugins\Editor\AzureSpatialAnchorsBridge_UnityEditor.cs'.

Best,
ephb

**Comment by DrScatman** [comment] 2020-08-11 20:48
I had a similar issue. I fixed it by simply deleting the **conflicting files** and then reimporting the SDK.

**Comment by TobiasPott** [comment] 2020-08-12 08:55
@DrScatman Can you check your code in Visual Studio (assuming you are running on Windows).
I've deleted the four files, reimported the latest SDK and opened the project there.
Afterwards I run a build from visual studio (just the solution) then the warnings/messages reappear for me.
Checking the files (in my case Android and UnityEditor) both files are enabled due to their pre-compiler directives matching the current state of the Unity Editor (build target is Android) which enable the UNITY_ANDROID and UNITY_EDITOR directives.

This seems to be only an issue inside the editor as the directives change for the actual build process in Unity (disabling the UNITY_EDITOR directive). It does not affect the build result in any way but is irritating when such a high number of warnings pop up in Unity or Visual Studio.

@ ASATeam: I've not checked the types inside the AzureSpatialAnchorsBridge_UnityEditor.cs affected by the warnings, but I assume that they are not required to be defined there (or at least not all of them) and I wonder whether this is a trade-off caused by some of your internal code-generation tool (indicated by a note in the files first lines ;)).

**Comment by craigktreasure** [comment] 2020-08-12 16:05
Thanks for the discussion everyone. We're preparing some changes to our Unity SDK for the next release and they resolve this issue. I realize that doesn't help now, but we do hear you on the frustration of the warnings and have a solution coming soon.

**Comment by TobiasPott** [comment] 2020-08-13 07:52
Hey @craigktreasure thank you for your response on this.
I'm happy to hear that you are aware of this and will address it with the next release.
As the warnings are irritating at best and not affect any functionality, I appreciate it very much. =)

**Comment by craigktreasure** [comment] 2020-09-09 03:28
This was fixed in 2.5.0 with the new UPM packages. Please open a new issue for additional feedback.

**Closed by craigktreasure** 2020-09-09 03:28 UTC
Labels: in next release
