### ISSUE TITLE
Build not work with xamarin

### ISSUE THREAD

**Issue by sely2k** [Azure/azure-spatial-anchors-samples#74] opened 2019-10-06 21:45 UTC
in xamarin project is referenced a package netstandard that is invalid
<img width="439" alt="Screenshot at Oct 06 23-38-18" src="https://user-images.githubusercontent.com/3965792/66276407-ff715f00-e892-11e9-9ce2-5b33c7e378d3.png">

**Comment by craigktreasure** [comment] 2019-10-28 21:12
I'm not able to reproduce your exact issue with a build error, but I'm definitely seeing some issues that I think are more Xamarin\Xcode issues. I do see the same issue in the **References** that you're seeing, but i'm still able to build and deploy the app. I was able to remove the **netstandard** reference and still build the sample, so we'll make that change in our next update to the samples.

**Comment by craigktreasure** [comment] 2019-11-14 19:04
This was fixed in our recent 2.0.0 release.

**Closed by craigktreasure** 2019-11-14 19:04 UTC
